### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by CodedNil** [CodedNil/home_flow#1]
- [ ] Top corners of walls remain unless all are disabled, needs to combine the deletion
- [ ] Furniture
  - [ ] Place/remove/set type
  - [ ] Popup menu to alter position, size, rotation and render options
  - [ ] Furniture can be stacked on other furniture such as light or tv on a table
  - [ ] Furniture can have states based on smart home, on/off etc
  - [ ] Render dynamically based on size and options, such as dining table also rendering chairs around it
- [ ] Lights
  - [ ] Sub category of furniture
  - [ ] Render light levels onto the rooms pixel layout, blocked by walls and with basic global illumination
  - [ ] Light comes in naturally from windows based on time of day/direction
- [ ] Temperatures
  - [ ] Render temperatures from sensors on the map
- [x] Walls
- [ ] Doors and windows
  - [ ] Defined with position and width, snaps to nearest wall when moving or when wall is altered
- [ ] Background, simplistic low res rendering out surrounding area
- [ ] Editing
  - [x] Add/remove/rename/reorder rooms
  - [x] Render room info and operations
  - [x] Drag rooms
    - [x] Snap edges to other rooms
    - [x] Drag operations
  - [x] Popup menus on rooms to alter position, size, operations and render options
  - [ ] Rewrite the operations display, render background colour for add/subtract, and drag and drop to reorder
  - [x] Load/edit layout data on server
  - [ ] Undo/redo
  - [ ] Preview changes before save
    - [x] Needs to update changes while its open
    - [x] Show more data in this
    - [ ] Delete button to revert line of edit
    - [ ] Scroll in preview window shouldnt zoom out of map
- [ ] AI editing, send photo of the room, and the app will send that along with a photo of the currently rendered floorplan, and the layout structs, and ai can propose changes such as resizing rooms, adding/altering furniture
- [ ] Smart home functionality
